// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/go-api/proto/api.proto

/*
Package go_micro_api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/go-api/proto/api.proto

It has these top-level messages:
	Pair
	Request
	Response
	Event
*/
package go_micro_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pair struct {
	Key    string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// A HTTP request as RPC
type Request struct {
	Method string           `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Path   string           `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Header map[string]*Pair `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Get    map[string]*Pair `protobuf:"bytes,4,rep,name=get" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Post   map[string]*Pair `protobuf:"bytes,5,rep,name=post" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body   string           `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// A HTTP response as RPC
type Response struct {
	StatusCode int32            `protobuf:"varint,1,opt,name=statusCode" json:"statusCode,omitempty"`
	Header     map[string]*Pair `protobuf:"bytes,2,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body       string           `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// A HTTP event as RPC
type Event struct {
	// e.g login
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// uuid
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	// unix timestamp of event
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// event headers
	Header map[string]*Pair `protobuf:"bytes,4,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// the event data
	Data string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "go.micro.api.Pair")
	proto.RegisterType((*Request)(nil), "go.micro.api.Request")
	proto.RegisterType((*Response)(nil), "go.micro.api.Response")
	proto.RegisterType((*Event)(nil), "go.micro.api.Event")
}

func init() { proto.RegisterFile("github.com/micro/go-api/proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x54, 0xe2, 0x24, 0x6c, 0x5e, 0x11, 0x42, 0x3e, 0x20, 0x6b, 0x85, 0x96, 0x92, 0x0b, 0xb9,
	0x90, 0xac, 0x76, 0x0f, 0x40, 0xaf, 0xa8, 0x02, 0x81, 0x90, 0x2a, 0xff, 0x81, 0xdb, 0x58, 0x89,
	0x05, 0x89, 0x4d, 0xec, 0x54, 0xea, 0x27, 0x72, 0xe6, 0x1b, 0xf8, 0x0f, 0x94, 0x17, 0xb7, 0x14,
	0x14, 0x4e, 0x85, 0xdb, 0xc4, 0x9a, 0x19, 0xcf, 0x9b, 0xe7, 0xc0, 0x8b, 0x5a, 0xb9, 0x66, 0xd8,
	0x16, 0x3b, 0xdd, 0x96, 0xad, 0xda, 0xf5, 0xba, 0xac, 0xf5, 0x4b, 0x61, 0x54, 0x69, 0x7a, 0xed,
	0x74, 0x29, 0x8c, 0x2a, 0x10, 0xd1, 0x87, 0xb5, 0x2e, 0x90, 0x50, 0x08, 0xa3, 0xb2, 0x5b, 0x88,
	0x36, 0x42, 0xf5, 0xf4, 0x31, 0x90, 0xcf, 0xf2, 0xc0, 0x82, 0x65, 0x90, 0xa7, 0x7c, 0x84, 0xf4,
	0x09, 0x24, 0x7b, 0xf1, 0x65, 0x90, 0x96, 0x85, 0x4b, 0x92, 0xa7, 0xdc, 0x7f, 0x65, 0xdf, 0x09,
	0x3c, 0xe0, 0xf2, 0xeb, 0x20, 0xad, 0x1b, 0x39, 0xad, 0x74, 0x8d, 0xae, 0xbc, 0xd0, 0x7f, 0x51,
	0x0a, 0x91, 0x11, 0xae, 0x61, 0x21, 0x9e, 0x22, 0xa6, 0x6f, 0x20, 0x69, 0xa4, 0xa8, 0x64, 0xcf,
	0xc8, 0x92, 0xe4, 0x8b, 0xbb, 0xe7, 0xc5, 0x79, 0x90, 0xc2, 0x5b, 0x16, 0xef, 0x91, 0xb3, 0xee,
	0x5c, 0x7f, 0xe0, 0x5e, 0x40, 0x6f, 0x81, 0xd4, 0xd2, 0xb1, 0x08, 0x75, 0x37, 0xf3, 0xba, 0x77,
	0xd2, 0x4d, 0xa2, 0x91, 0x4a, 0xef, 0x21, 0x32, 0xda, 0x3a, 0x16, 0xa3, 0xe4, 0xd9, 0xbc, 0x64,
	0xa3, 0xad, 0xd7, 0x20, 0x79, 0x4c, 0xbd, 0xd5, 0xd5, 0x81, 0x25, 0x53, 0xea, 0x11, 0x5f, 0x7f,
	0x82, 0xc5, 0x59, 0xa2, 0x99, 0x9a, 0x72, 0x88, 0xb1, 0x18, 0x9c, 0x75, 0x71, 0x47, 0x7f, 0xbf,
	0x6a, 0xec, 0x96, 0x4f, 0x84, 0x55, 0xf8, 0x3a, 0xb8, 0xfe, 0x00, 0x57, 0xc7, 0xa0, 0x17, 0x7b,
	0x7d, 0x84, 0xf4, 0x34, 0xc1, 0xa5, 0x66, 0xd9, 0xb7, 0x00, 0xae, 0xb8, 0xb4, 0x46, 0x77, 0x56,
	0xd2, 0x1b, 0x00, 0xeb, 0x84, 0x1b, 0xec, 0x5b, 0x5d, 0x49, 0xf4, 0x8c, 0xf9, 0xd9, 0x09, 0x5d,
	0x9d, 0x56, 0x19, 0x62, 0xbf, 0xd9, 0x9f, 0xfd, 0x4e, 0x3e, 0xb3, 0xbb, 0x3c, 0x96, 0x4c, 0xfe,
	0x5b, 0xc9, 0xd9, 0x8f, 0x00, 0xe2, 0xf5, 0x5e, 0x76, 0xb8, 0xd1, 0x4e, 0xb4, 0xd2, 0x5b, 0x21,
	0xa6, 0x8f, 0x20, 0x54, 0x95, 0x7f, 0x99, 0xa1, 0xaa, 0xe8, 0x53, 0x48, 0x9d, 0x6a, 0xa5, 0x75,
	0xa2, 0x35, 0x98, 0x8a, 0xf0, 0x5f, 0x07, 0xf4, 0xd5, 0x69, 0xd4, 0x68, 0xee, 0x29, 0xe1, 0x35,
	0x7f, 0x9b, 0xb3, 0x12, 0x4e, 0xb0, 0x78, 0xba, 0x7a, 0xc4, 0xff, 0x78, 0xce, 0x6d, 0x82, 0x3f,
	0xf4, 0xfd, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x99, 0x8a, 0x99, 0xfb, 0x03, 0x00, 0x00,
}
